"""UI 布局尺寸与间距 Token。"""

PAGE_MARGIN = 24
DIALOG_MARGIN = 24
DIALOG_BOTTOM_MARGIN = 20
SECTION_SPACING = 16
CONTROL_SPACING = 8
FORM_SPACING = 10
BUTTON_HEIGHT = 32
SMALL_BUTTON_HEIGHT = 28

SMALL_DIALOG_WIDTH = 320
MEDIUM_DIALOG_WIDTH = 420
LARGE_DIALOG_WIDTH = 760
CALENDAR_DIALOG_WIDTH = 820
TABLE_DIALOG_WIDTH = 720
